### ISSUE TITLE
Show JSON repsonse from API

### ISSUE THREAD

**Issue by mdsauce** [enriquegh/sauce-log-parser#21]
File "/home/max/workspace/sauce/sauce-log-parser/sauce_job.py", line 30, in fetch_log
While running the command below I get an exception at line 30 for sauce_job.py.  I suspect I'm rate limited but have no easy way to confirm.

```
$ python sel_log_parser.py -a $SAUCE_USERNAME -k $SAUCE_EU_ACCESS_KEY -u tinsauce 0f20d4e3f2eb4868ab859d4f4bcc0686
Traceback (most recent call last):
  File "sel_log_parser.py", line 129, in <module>
    main()
  File "sel_log_parser.py", line 120, in main
    args.access_key, args.user, args.save)
  File "/home/max/workspace/sauce/sauce-log-parser/sauce_job.py", line 30, in fetch_log
    self.data = json.loads(response.decode())
  File "/home/max/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/max/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/max/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by enriquegh** [comment]
You should be able to get more info with -v now.
In this case, it's a 404 message that we get meaning the test doesn't exist.

We should have an additional feature to be more graceful and not crash though.
